<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{5f92e3a5-cf76-46ea-baeb-96201743b010}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Counter	:UDINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Counter:=Counter-1;

//Programer 2 change]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>